### ISSUE TITLE
Enkel laatste feedback zichtbaar

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#12]
Bij een student heb ik eerst een opmerking gegeven en het voorstel afgekeurd, en daarna goedgekeurd.

Ik zie in de historiek enkel de laatste evaluatie, niet de feedback op het eerste voorstel

**Comment by Aaronmsv** [comment]
Ik ga hierover een test schrijven/terugnemen en eens bekijken. 

> Is de tekst van de pdf wijzigbaar zonder hercompileren? Bv. "Schooljaar -> academiejaar" en iets vermelden van de bachproef op de voorpagina. 

Nu wel, ik heb dit net localized gemaakt. Je kan deze strings aanpassen in "/App_GlobalResources/LocalizedText.resx", let wel op voor trailing spaces, hoofdletters en dergelijke.

Om iets op de voorpagina te schrijven moet je de value van de key: DocumentResources_PrintTitlePage_Message aanpassen. Momenteel is deze leeg. Dit is wel in plain text.

**Comment by Aaronmsv** [comment]
In verband met feedback die zou verdwijnen, wij krijgen kunnen dit echt niet reproduceren. Wij hebben een nieuwe DB initialisatie gemaakt met exact deze situatie en daar is alles normaal, daarnaast werkt het manueel ook zoals verwacht. Ik vermoed daarom dat dit opgelost is.

> In de kolom "propositions" is het veld Student_UserId altijd "null". Is dat normaal?

Ja. Het student model houdt het id van het huidige voorstel bij en daarom is het id in de proposition null. Wanneer een student echter meerdere propositions heeft, dan houden deze (uitgezonderd de huidige) het id van de student bij.
