### ISSUE TITLE
Activatiemail opnieuw zenden

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#13]
Sommige gebruikers verliezen hun activatiemail of hebben niet door dat ze de link moeten volgen en proberen meteen in te loggen. Daarom zou het interessant zijn om voor een gebruiker de activatiemail opnieuw te kunnen verzenden.

**Comment by Aaronmsv** [comment]
Deze feature is nu beschikbaar voor admins en kan je vinden op het overzicht van een student.
