### ISSUE TITLE
Feedbacks tabel heeft "lege" records

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#14]
In de feedbacks-tabel zijn sommige records "leeg": de datum staat op "0001-01-01" en het Remarks veld is null.

![selection_018](https://cloud.githubusercontent.com/assets/438140/5691886/ddd3124a-98dc-11e4-95f4-e9808e180cb4.png)

**Comment by Aaronmsv** [comment]
Dit is normaal. Vanaf een promotor op "Evalueer voorstel" drukt worden de Feedback en Score models aangemaakt en opgeslagen. De kolom Submitted blijf "leeg" tot de promotor het voorstel indient (en niet opslaat). De kolom Remarks blijft leeg zolang de promotor geen opmerkingen toevoegt.

Het werkt op die manier omdat er een opslaan en indien feature is.
