### ISSUE TITLE
Globale deadline wordt niet getoond op de admin-pagina

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#17]
Als er een globale deadline is ingesteld, wordt die toch niet getoond op de admin-pagina:

![image](https://cloud.githubusercontent.com/assets/438140/5719073/05547716-9b15-11e4-84bc-de7b59bad7d9.png)

**Comment by Aaronmsv** [comment]
Wel, het is niet echt mogelijk om dat te doen, tenzij via een omweg. Dit komt doordat u de deadline instelt bij elke student apart, maar daarna kan de promotor (of u) deze deadline wijzigen. U kan er dus nooit zeker van zijn dat alle studenten nog steeds dezelfde deadline hebben, tenzij u wilt dat dit berekend wordt.

Hoe wilt u dit oplossen:

* Dit kan berekend worden
* U kan dit bekijken bij een specifieke student (maar blijkbaar staat dit niet op het overzicht?)
* Dit kan als kolom toegevoegd worden aan de lijst van studenten bij dossiers

**Comment by bertvv** [comment]
Ok, dat snap ik.

Maar dan moet er bij het aanpassen van de globale deadline wel op gelet worden dat individueel ingestelde deadlines (door de promotor) niet vervroegen.

Een fictief scenario als voorbeeld: Ik stel de deadline in op 15 december, en een student vraag aan haar promotor om dit naar 21 december uit te stellen omdat ze dan een afspraak heeft op haar stageplaats. De promotor doet dit. Maar dan blijkt dat 15 december een ongelukkig gekozen datum is, en dat we met de promotoren afspreken dat het de 18e mag worden. Als ik de algemene aanpassing doe vanop de admin-pagina, zou het niet ok zijn als de datum van de student van hierboven ineens 3 dagen vervroegd wordt.
