### ISSUE TITLE
Bij onderwerpen die opnieuw ingediend zijn is het niet mogelijk de historiek te zien

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#22]
Als een student na het afkeuren opnieuw een voorstel indient, komt het opnieuw in de toestand "Voorstel in behandeling". Het is dan echter niet meer mogelijk om in het detailzicht de historiek op te vragen van het voorstel. Als promotor kan je dus niet nakijken wat de feedback was bij het vorige voorstel en in hoeverre de student rekening gehouden heeft met de opmerkingen.

Wie de URL-structuur van de applicatie kent, kan de juiste URL construeren, maar dit zou in de app zelf moeten kunnen. 

Een mogelijke oplossing is op de pagina /Promotor/Evaluate/USERID een knop toe te voegen met een link naar /Record/History/USERID

**Comment by Aaronmsv** [comment]
Het was wel nog mogelijk om dit te bekijken via dossiers -> student, maar een link kan inderdaad wel handig zijn. Een link naar het dossier en ook historiek is toegevoegd onderaan aan de pagina.
