### ISSUE TITLE
Advies vragen voor tweede student geeft foutmelding

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#25]
Een promotor had advies gevraagd voor een student en wou hetzelfde doen voor een tweede. De volgende foutboodschap verscheen:

![error_advies](https://cloud.githubusercontent.com/assets/438140/6185345/95d0b5c8-b36d-11e4-80b5-6fd6e1271207.png)

Er werd een notificatie gestuurd naar de BPC, maar het dossier is niet te zien in de lijst "wachtend op advies"

**Comment by Aaronmsv** [comment]
Ik heb dit kunnen reproduceren, maar krijg wel een andere fout: 

> ObjectDisposedException: The ObjectContext instance has been disposed and can no longer be used for operations that require a connection

Die errorlog is hier niet aan gerelateerd denk ik. Beide hebben echter te maken met de database connectie. Het heeft waarschijnlijk iets te maken met het moment waarop SaveChanges() wordt opgeroepen, maar ik moet het verder bekijken.
