### ISSUE TITLE
Verplaatsen copromotor

### ISSUE THREAD

**Issue by Aaronmsv** [Aaronmsv/Bachelorproefportal-TI#26]
Ik ben begonnen met het verplaatsen van de copromotor als User naar properties. Zie branche MoveCopromotor.

Ik zou dit graag wel eens eerst overlopen voor ik de controllers aanpas. Is de copromotor nu verplicht? Mag dit in stukken (of niet ingevuld) worden wanneer de gebruiker het voorstel bewaart maar niet indient?

**Comment by bertvv** [comment]
De co-promotor is verplicht.

Als een voorstel bewaard wordt, maar nog niet doorgestuurd, hoeft geen enkel verplicht veld al ingevuld te zijn. Dit moet enkel gecontroleerd worden bij definiitef indienen.

**Comment by Aaronmsv** [comment]
OK, ik heb dit met Chris afgewerkt en dit zou nu in orde moeten zijn. Het zou eigenlijk wel eerst zeer goed getest moeten worden.
