### ISSUE TITLE
Vereenvoudiging onderzoeksdomeinen

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#28]
De manier waarop ik de onderzoeksdomeinen geconcipieerd heb blijkt in de praktijk eigenlijk veel te ingewikkeld om bruikbaar te zijn (my bad!).

Het zou beter zijn om dit te beperken tot een kleiner aantal categorieën, meer bepaald de keuzevakken van het laatste jaar:
- systeem- en netwerkbeheer
- ontwikkeling van webapplicaties
- ontwikkeling van mobiele applicaties
- software-ontwikkeling   [= al wat niet onder de 2 vorige categorieën valt]
- mainframe
- databanken 
- e-business
- andere

Maar dit is misschien enkel een kwestie van dit in de databank zo in te vullen?

**Comment by Aaronmsv** [comment]
Dat is inderdaad een databank kwestie. Wij hebben zitten denken om die seed te verwijderen uit de code en een XML bestand in te lezen wanneer de DB leeg is. In de XML zitten dan de admin accounts die aangemaakt moeten worden en o.a. de onderzoeksdomeinen. Wat denkt u daarvan?

**Comment by bertvv** [comment]
Een extern configuratiebestand voor de opstart is prima. Of XML het meest praktische formaat is, daar valt over te discussiëren (Yaml?), maar ik heb daar geen bezwaar tegen.

**Comment by Aaronmsv** [comment]
Chris ziet het eventueel wel zitten om het aanpassen van de onderzoeksdomeinen, e-mails, Likert vragen en dergelijke op de website te ondersteunen. Voor de admin accounts is dat wel moeilijker. Zeker voor het eerste account. Ofwel moet er een default admin account komen (waarvan u dan later de eigenschappen kan veranderen), ofwel moet dat gedaan worden via een console project of zoiets,

**Comment by bertvv** [comment]
Ik heb nu voor mezelf ook al een apart admin-account en een promotor-account aangemaakt. Zo zie ik zelf goed het verschil en kan ik de collega's die vragen hebben beter ondersteunen.

Dus dat is voor mij zeker aanvaardbaar als oplossing.

**Comment by cdd1** [comment]
over de onderzoeksdomeinen, betekent dit dat 'subonderzoeksdomeinen' niet meer nodig zijn en mogen verdwijnen uit het project? En wilt u het aanpassen/toevoegen/verwijderen van onderzoeksdomeinen op de website hebben? Dit om ook zoveel mogelijk problemen met aanpassingen rechtstreeks in de database te vermijden.

**Comment by bertvv** [comment]
subonderzoeksdomeinen mogen inderdaad verdwijnen.
CRUD in de website is een "nice to have", dus niet prioritair
