### ISSUE TITLE
Functionaliteit "verwijder geselecteerde studenten" hoort niet thuis onder kop "Exporteer naar PDF"

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#31]
In de Admin-console staat "verwijder geselecteerde studenten" onder "Exporteer naar PDF":

![image](https://cloud.githubusercontent.com/assets/438140/8216373/7148c6fc-1536-11e5-933e-293ed332c0d6.png)

Dit lijkt me geen geschikte plaats, aangezien studenten verwijderen niets te maken heeft met de export. Tenminste als "studenten verwijderen" betekent het effectief verwijderen van studenten uit de database, bijvoorbeeld in de overgang van de 1e naar 2e zittijd. Als het echter betekent dat ze niet mee opgenomen worden in de pdf, maar wel in de databank blijven, dan zou dit duidelijker verwoord moeten worden.

**Comment by Aaronmsv** [comment]
De studenten worden daar wel degelijk verwijdert uit de database. Hoe wil je het dan liefst? Een aparte sectie eronder?

**Comment by bertvv** [comment]
Dat lijkt me inderdaad passend

**Comment by Aaronmsv** [comment]
Nu dat ik de code nog eens bekijk, blijft het wel beter op deze manier. Je hebt nu de mogelijkheid om de studenten te selecteren die je wenst te printen of te verwijderen. Ik zal het anders verwoorden.

**Comment by Aaronmsv** [comment]
Zoiets?
![image](http://i.imgur.com/xXUcz5A.png)

**Comment by bertvv** [comment]
Ik kan hier mee leven. De kop wordt dan ook best aangepast, bv. "Studenten verwijderen/exporteren"

Let op dt-fouten! ;)

**Comment by Aaronmsv** [comment]
Aangepast.
